sudo: required
services:
  - docker

before_install:
  - docker build -t docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true docker-react-app npm run test

deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESS_KEY_ID
  secret_access_key:
    secure: "$SECRET_ACCESS_KEY"
  region: "ap-south-1"
  app: "docker-react-app"
  env: "Dockerreactapp-env"
  bucket_name: "elasticbeanstalk-ap-south-1-342944276367"
  bucket_path: "docker-react-app"
  on:
    branch: main